#!/usr/bin/env bash
#configures an Ubuntu server (change IP)
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0./127.0.0.2/ ~/hosts.new
sed -i "\$a8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts